<?php

namespace App\Console\Commands;

use App\Models\PlatformAdmin;
use App\Support\ReadablePassword;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Validator;

/**
 * The only way the first operator account comes into existence.
 *
 * There is no signup for the portal and there must not be one — an open
 * registration form on a cross-tenant tool is the whole problem the shared
 * secret had, with better UX. So the first account is made over SSH on the
 * box, and every account after that is made by an owner from inside the
 * portal. This command is also the break-glass path when the last owner locks
 * themselves out.
 */
class CreatePlatformAdmin extends Command
{
    protected $signature = 'platform:admin-create
        {--name= : Full name}
        {--email= : Login email}
        {--role=owner : owner or operator}
        {--password= : Leave unset to have one generated}';

    protected $description = 'Create a platform operator account for the super admin portal';

    public function handle(): int
    {
        $name = $this->option('name') ?: $this->ask('Full name');
        $email = $this->option('email') ?: $this->ask('Email');
        $role = $this->option('role');

        // Generated by default: a password typed at a prompt on a shared box
        // ends up in shell history, and this one only has to survive being
        // read once before it is changed.
        $password = $this->option('password') ?: ReadablePassword::generate();
        $generated = ! $this->option('password');

        $validator = Validator::make(
            ['name' => $name, 'email' => $email, 'role' => $role, 'password' => $password],
            [
                'name' => ['required', 'string', 'max:255'],
                'email' => ['required', 'email', 'max:255', 'unique:platform_admins,email'],
                'role' => ['required', 'in:'.implode(',', PlatformAdmin::ROLES)],
                'password' => ['required', 'string', 'min:12'],
            ],
        );

        if ($validator->fails()) {
            foreach ($validator->errors()->all() as $message) {
                $this->components->error($message);
            }

            return self::FAILURE;
        }

        $admin = PlatformAdmin::create([
            'name' => $name,
            'email' => $email,
            'role' => $role,
            'password' => $password,
            'status' => PlatformAdmin::STATUS_ACTIVE,
        ]);

        $this->components->info("Created {$admin->role} account for {$admin->email}.");

        if ($generated) {
            $this->components->twoColumnDetail('Password', $password);
            $this->components->warn('Shown once. Nothing stores the plaintext.');
        }

        return self::SUCCESS;
    }
}
