<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import type { ExpressionSpecification, Map as MapboxMap, Marker } from 'mapbox-gl'
import {
  animateMarker,
  fetchDrivingRoute,
  fitToPoints,
  haversineKm,
  isPoint,
  loadMapbox,
  mapboxStyleFor,
  mapsAvailable,
  type LatLng,
} from '@pos/core/maps/mapbox'

/**
 * Where the rider is, on a map, while they are on the way.
 *
 * One component for both audiences, because they want the same three things on
 * screen — the shop, the door, and the person between them — and two versions
 * of this would drift until the merchant and the customer were looking at
 * different pictures of the same delivery while on the phone to each other.
 *
 * What differs is only what the caller passes in: the customer's copy gets a
 * position that the API withholds after handover, the merchant's does not.
 * That rule lives in the API (Order::riderPositionForCustomer), not here — a
 * privacy boundary enforced in a Vue component is a privacy boundary that ends
 * at the first person who opens the network tab.
 *
 * Degrades in four steps, none of which is an error message:
 *   - no token, no WebGL, no library → the stage line alone
 *   - a map but no rider position → shop and door, and where the order is
 *   - a rider, model still on the wire → the halo, easing along the road
 *   - everything → the scooter itself, turned the way the rider is going
 *
 * That third step is not a fallback that had to be built; it is what the map
 * looks like for the second or two the 880 KB model takes to arrive, and on a
 * bad connection it is what it looks like for the whole delivery. The halo
 * carries the position, the liveness and the stale state on its own, so a
 * model that never turns up costs the viewer nothing they needed.
 */

const props = withDefaults(
  defineProps<{
    /** The shop. Drawn as a square pin, and the start of the route. */
    pickup?: { name?: string | null; address?: string | null; lat?: number | null; lng?: number | null } | null
    /** The customer's door. */
    dropoff?: { address?: string | null; lat?: number | null; lng?: number | null } | null
    /** Latest fix, as the API serves it. Null means nobody is reporting. */
    rider?: {
      lat: number
      lng: number
      headingDeg?: number | null
      speedKph?: number | null
      at?: string | null
      ageSeconds?: number | null
      stale?: boolean
    } | null
    riderName?: string | null
    /** pending | assigned | picked_up | delivered. Decides the caption. */
    stage?: string | null
    /** Follows the app's own appearance so the map doesn't glare at night. */
    dark?: boolean
    height?: string
  }>(),
  { height: '260px', dark: false },
)

const container = ref<HTMLDivElement | null>(null)
const failed = ref(false)
const ready = ref(false)

let map: MapboxMap | null = null
let pickupMarker: Marker | null = null
let dropoffMarker: Marker | null = null
let cancelAnimation: (() => void) | null = null
let lastRiderPoint: LatLng | null = null
let hasFitted = false
let haloFrame: number | null = null
let riderLayersPending = false

/**
 * The scooter, its rider and their top box, generated by
 * `scripts/build-rider-model.py` and written to both this app's `public/` and
 * the Android rider app's assets. One generator, so the customer's map and the
 * rider's own map cannot end up disagreeing about what a delivery looks like.
 */
const RIDER_MODEL_URL = '/delivery/rider.glb'
const RIDER_MODEL_ID = 'omaykan-rider'
const RIDER_SOURCE = 'delivery-rider'
const RIDER_HALO = 'delivery-rider-halo'
const RIDER_MODEL = 'delivery-rider-model'

/**
 * How big the scooter is drawn, as a zoom-indexed multiplier.
 *
 * A `model` layer is scaled in *world* metres, so a fixed number would make a
 * 2.5 m bike 400 px wide in a street and a fifth of a pixel across the city.
 * Halving the multiplier for every zoom level in cancels that exactly and
 * leaves the marker a constant size on screen, the way the pin it replaces
 * always behaved. The base-0.5 exponential is what makes the interpolation
 * geometric rather than linear between the two stops.
 */
const RIDER_SCALE: ExpressionSpecification = [
  'interpolate',
  ['exponential', 0.5],
  ['zoom'],
  10,
  ['literal', [3276.8, 3276.8, 3276.8]],
  20,
  ['literal', [3.2, 3.2, 3.2]],
]

const pickupPoint = computed<LatLng | null>(() =>
  isPoint(props.pickup ?? undefined) ? { lat: props.pickup!.lat!, lng: props.pickup!.lng! } : null,
)
const dropoffPoint = computed<LatLng | null>(() =>
  isPoint(props.dropoff ?? undefined) ? { lat: props.dropoff!.lat!, lng: props.dropoff!.lng! } : null,
)
const riderPoint = computed<LatLng | null>(() =>
  isPoint(props.rider ?? undefined) ? { lat: props.rider!.lat, lng: props.rider!.lng } : null,
)

/** Nothing to draw at all — not even the two ends. Skip the canvas entirely. */
const drawable = computed(
  () => mapsAvailable() && (pickupPoint.value !== null || dropoffPoint.value !== null || riderPoint.value !== null),
)

/**
 * The line under the map, in words.
 *
 * Deliberately the same sentence whether or not the map rendered, because it is
 * the fallback as well as the caption — and because a distance is what people
 * actually read off a delivery map. Straight-line kilometres, described as
 * such: quoting road distance from a straight line is how "2 minutes away"
 * becomes a complaint.
 */
const caption = computed(() => {
  const name = props.riderName?.trim() || 'The rider'

  if (props.stage === 'delivered') return 'Delivered.'
  if (!props.rider) {
    if (props.stage === 'assigned') return `${name} is on the way to the shop.`
    if (props.stage === 'picked_up') return `${name} has the order and is on the way.`
    return 'Waiting for a rider to take this one.'
  }

  if (props.rider.stale) {
    const minutes = Math.max(1, Math.round((props.rider.ageSeconds ?? 0) / 60))
    return `Last seen ${minutes} minute${minutes === 1 ? '' : 's'} ago — ${name}'s phone has gone quiet.`
  }

  const target = props.stage === 'picked_up' ? dropoffPoint.value : pickupPoint.value
  if (!target || !riderPoint.value) {
    return props.stage === 'picked_up' ? `${name} is on the way to you.` : `${name} is heading to the shop.`
  }

  const km = haversineKm(riderPoint.value, target)
  const distance = km < 1 ? `${Math.round(km * 1000)} m` : `${km.toFixed(1)} km`
  const where = props.stage === 'picked_up' ? 'from you' : 'from the shop'

  return `${name} is about ${distance} ${where}, in a straight line.`
})

// -- Building the map ---------------------------------------------------------

function pinElement(kind: 'pickup' | 'dropoff'): HTMLDivElement {
  const el = document.createElement('div')
  el.className = `delivery-map__pin delivery-map__pin--${kind}`
  el.setAttribute('aria-hidden', 'true')
  return el
}

/** The rider's position, in the shape the source wants it. */
function riderFeature(point: LatLng) {
  return {
    type: 'Feature' as const,
    properties: {},
    geometry: { type: 'Point' as const, coordinates: [point.lng, point.lat] as [number, number] },
  }
}

/**
 * Put the rider on the map: a halo on the ground, the scooter above it.
 *
 * Both layers read the same source, so moving the rider is one `setData` and
 * the two can never separate. Safe to call again — on a style swap it has to
 * be, because `setStyle` drops every source, layer and model the app added.
 */
async function addRiderLayers(target: MapboxMap, point: LatLng) {
  if (riderLayersPending) return
  riderLayersPending = true

  try {
    // On a style swap this runs from `styledata`, at which point the new style
    // is announced but not yet ready to be added to. Waiting is the difference
    // between the rider surviving a switch to dark mode and vanishing on it.
    await styleReady()
    if (map !== target) return
    if (target.getSource(RIDER_SOURCE)) return void setRiderPoint(point)

    addRiderLayersNow(target, point)
  } finally {
    riderLayersPending = false
  }
}

function addRiderLayersNow(target: MapboxMap, point: LatLng) {
  target.addSource(RIDER_SOURCE, { type: 'geojson', data: riderFeature(point) })

  // The halo goes on whether or not the model ever arrives, and is drawn to
  // stand alone: on a slow line it is the marker, not a decoration under one.
  target.addLayer({
    id: RIDER_HALO,
    type: 'circle',
    source: RIDER_SOURCE,
    paint: {
      'circle-radius': 13,
      'circle-color': props.dark ? '#7dd3fc' : '#2563eb',
      'circle-opacity': 0.28,
      'circle-stroke-width': 2,
      'circle-stroke-color': '#fff',
      'circle-stroke-opacity': 0.9,
    },
  })

  try {
    // Throws if the id is already registered, which happens when a style swap
    // and a fresh position race each other. Nothing to do about it but carry
    // on — the model is still there under that id.
    if (!target.hasModel?.(RIDER_MODEL_ID)) target.addModel(RIDER_MODEL_ID, RIDER_MODEL_URL)
  } catch {
    /* already registered */
  }

  target.addLayer({
    id: RIDER_MODEL,
    type: 'model',
    source: RIDER_SOURCE,
    layout: { 'model-id': RIDER_MODEL_ID },
    paint: {
      'model-scale': RIDER_SCALE,
      'model-rotation': [0, 0, 0],
      'model-type': 'common-3d',
      // Classic styles carry no 3D lighting rig, so an unlit model reads as a
      // dark smudge on a pale map. A little emission is what keeps the green
      // green at midday.
      'model-emissive-strength': 0.3,
      'model-cast-shadows': false,
    },
  })

  applyRiderPaint()
  startHalo()
}

/**
 * The pulse, and the grey.
 *
 * Heading turns the model rather than an icon, and the sign is the whole
 * subtlety: a compass bearing runs clockwise from north and the layer's
 * z rotation runs the other way, so it is negated. Getting this backwards is
 * invisible while a rider heads north and obvious the moment they turn.
 */
function applyRiderPaint() {
  if (!map?.getLayer(RIDER_MODEL)) return

  const stale = props.rider?.stale === true
  const heading = props.rider?.headingDeg

  // No bearing means standing still. Leaving the last one is better than
  // snapping to north, which reads as the bike suddenly turning.
  if (typeof heading === 'number' && Number.isFinite(heading)) {
    map.setPaintProperty(RIDER_MODEL, 'model-rotation', [0, 0, -heading])
  }

  // Gone quiet: the scooter greys out, so a stopped rider never looks the same
  // as a moving one. Mixing toward grey rather than swapping the model keeps
  // the shape — it is the same rider, just not reporting.
  map.setPaintProperty(RIDER_MODEL, 'model-color', stale ? '#8b93a1' : '#ffffff')
  map.setPaintProperty(RIDER_MODEL, 'model-color-mix-intensity', stale ? 0.8 : 0)

  if (map.getLayer(RIDER_HALO)) {
    map.setPaintProperty(RIDER_HALO, 'circle-color', stale ? '#6b7280' : props.dark ? '#7dd3fc' : '#2563eb')
  }
}

/** Two seconds of breathing, so a live marker never looks like a screenshot. */
function startHalo() {
  stopHalo()
  if (window.matchMedia?.('(prefers-reduced-motion: reduce)').matches) return

  const started = performance.now()
  const tick = (now: number) => {
    if (!map?.getLayer(RIDER_HALO)) return
    if (props.rider?.stale) {
      // A stale marker stops breathing. That is the signal.
      map.setPaintProperty(RIDER_HALO, 'circle-radius', 13)
      map.setPaintProperty(RIDER_HALO, 'circle-opacity', 0.2)
    } else {
      const phase = ((now - started) % 2000) / 2000
      map.setPaintProperty(RIDER_HALO, 'circle-radius', 11 + phase * 14)
      map.setPaintProperty(RIDER_HALO, 'circle-opacity', 0.32 * (1 - phase))
    }
    haloFrame = requestAnimationFrame(tick)
  }
  haloFrame = requestAnimationFrame(tick)
}

function stopHalo() {
  if (haloFrame !== null) cancelAnimationFrame(haloFrame)
  haloFrame = null
}

/**
 * Resolves when the style will accept `addSource` — now, or at the next idle.
 *
 * `idle` rather than `styledata`: the model is fetched after the style event
 * fires, and idle is the one signal that means every outstanding request has
 * landed.
 */
function styleReady(): Promise<void> {
  return new Promise((resolve) => {
    if (!map || map.isStyleLoaded()) return resolve()
    map.once('idle', () => resolve())
  })
}

/** Move the rider. One call, both layers, because they share the source. */
function setRiderPoint(point: LatLng) {
  const source = map?.getSource(RIDER_SOURCE) as { setData?: (data: unknown) => void } | undefined
  source?.setData?.(riderFeature(point))
}

async function build() {
  if (!container.value || !drawable.value) return

  const mapbox = await loadMapbox()
  if (!mapbox || !container.value) {
    failed.value = true
    return
  }

  try {
    map = new mapbox.Map({
      container: container.value,
      style: mapboxStyleFor(props.dark),
      center: [
        (riderPoint.value ?? pickupPoint.value ?? dropoffPoint.value)!.lng,
        (riderPoint.value ?? pickupPoint.value ?? dropoffPoint.value)!.lat,
      ],
      zoom: 14,
      // A tracking map is read, not explored. Rotation and pitch on a phone
      // are almost always an accident, and a map nobody can un-rotate looks
      // broken to the person holding it.
      pitchWithRotate: false,
      dragRotate: false,
      attributionControl: true,
    })

    map.touchZoomRotate?.disableRotation()
    map.addControl(new mapbox.NavigationControl({ showCompass: false }), 'top-right')

    if (pickupPoint.value) {
      pickupMarker = new mapbox.Marker({ element: pinElement('pickup') })
        .setLngLat([pickupPoint.value.lng, pickupPoint.value.lat])
        .addTo(map)
    }

    if (dropoffPoint.value) {
      dropoffMarker = new mapbox.Marker({ element: pinElement('dropoff') })
        .setLngLat([dropoffPoint.value.lng, dropoffPoint.value.lat])
        .addTo(map)
    }

    if (riderPoint.value) lastRiderPoint = riderPoint.value

    map.on('load', async () => {
      ready.value = true
      if (!hasFitted) {
        fitToPoints(map!, [pickupPoint.value, dropoffPoint.value, riderPoint.value].filter(Boolean) as LatLng[])
        hasFitted = true
      }
      // The rider is layers, not a DOM marker, so unlike the two pins it has
      // to wait for the style. Awaited before the route so that the route can
      // find the halo to slide underneath.
      if (map && riderPoint.value) await addRiderLayers(map, riderPoint.value)
      void drawRoute()
    })
  } catch {
    // WebGL unavailable is the usual cause, and there is nothing to say about
    // it that helps — the caption below still answers the question.
    failed.value = true
    map = null
  }
}

/**
 * The road the order is travelling, as a line under the markers.
 *
 * Drawn from where the rider is to where they are going, so it shortens as they
 * move rather than sitting there as a fixed shop-to-door decoration. Before a
 * rider exists it is shop-to-door, which is the trip about to be made.
 */
async function drawRoute() {
  if (!map) return

  // With a rider on the map the line is the leg they are actually on: to the
  // shop before pickup, to the door after. Without one it is the whole trip,
  // shop to door — the journey about to be made.
  const rider = riderPoint.value
  const from = rider ?? pickupPoint.value
  const to = rider
    ? (props.stage === 'picked_up' ? dropoffPoint.value : pickupPoint.value)
    : dropoffPoint.value

  if (!from || !to || from === to) return

  const path = (await fetchDrivingRoute(from, to)) ?? [from, to]
  const isRealRoad = path.length > 2

  // Both awaits in this function have to be behind this, not in front of it.
  // Registering the scooter leaves the style with a fetch outstanding, and a
  // style with work outstanding both reports `isStyleLoaded()` false *and*
  // throws from `addSource`. Checking once at the top — which is what this
  // used to do — returned early and left the delivery with no route line at
  // all until the next ping happened to redraw it.
  await styleReady()
  if (!map) return

  const geojson = {
    type: 'Feature' as const,
    properties: {},
    geometry: {
      type: 'LineString' as const,
      coordinates: path.map((p) => [p.lng, p.lat] as [number, number]),
    },
  }

  if (!map) return

  const existing = map.getSource('delivery-route') as { setData?: (data: unknown) => void } | undefined
  if (existing?.setData) {
    existing.setData(geojson)
    return
  }

  map.addSource('delivery-route', { type: 'geojson', data: geojson })
  map.addLayer(
    {
      id: 'delivery-route',
      type: 'line',
      source: 'delivery-route',
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': props.dark ? '#7dd3fc' : '#0ea5e9',
        'line-width': 4,
        'line-opacity': 0.8,
        // Dashed when it is a guess. A straight line drawn solid reads as a
        // route the rider is following, and it isn't one.
        ...(isRealRoad ? {} : { 'line-dasharray': [1.5, 1.5] }),
      },
    },
    // Under the rider. The two pins are DOM markers in Mapbox's own overlay
    // and sit above the canvas whatever happens, but the rider is a real layer
    // now — and a 4px line drawn over the scooter's front wheel looks like the
    // road has been painted on top of it.
    map.getLayer(RIDER_HALO) ? RIDER_HALO : undefined,
  )
}

// -- Reacting to new pings ----------------------------------------------------

watch(riderPoint, async (next) => {
  if (!next) return

  if (!map) {
    // The first fix can arrive before the map was worth building — an order
    // that had no coordinates at all until a rider took it.
    if (drawable.value && !failed.value) await build()
    return
  }

  // The first fix of a delivery can land before the style has finished, in
  // which case the load handler puts the rider on instead.
  if (!map.getSource(RIDER_SOURCE)) {
    await addRiderLayers(map, next)
    lastRiderPoint = next
    void drawRoute()
    return
  }

  cancelAnimation?.()
  const from = lastRiderPoint ?? next

  // A jump of more than a couple of kilometres between pings is a phone that
  // was in a dead spot, not a bike that moved. Animating it draws a straight
  // line across the city at an impossible speed; snapping is the truth.
  if (haversineKm(from, next) > 2) {
    setRiderPoint(next)
  } else {
    cancelAnimation = animateMarker((point) => setRiderPoint(point), from, next)
  }

  lastRiderPoint = next
  applyRiderPaint()
  void drawRoute()

  // Follow the rider only when they have left the view. Recentring on every
  // ping takes the map away from anyone trying to look at the rest of it.
  if (!map.getBounds()?.contains([next.lng, next.lat])) {
    map.easeTo({ center: [next.lng, next.lat], duration: 800 })
  }
})

watch(
  () => props.stage,
  () => {
    // Pickup done: the interesting half of the trip is now the second one.
    void drawRoute()
  },
)

watch(
  () => props.dark,
  (dark) => {
    if (!map) return
    map.setStyle(mapboxStyleFor(dark))
    // A style swap drops every source and layer the app added. The two pins
    // are DOM and survive; the route line and the whole rider — source, halo,
    // model and the registered model itself — do not, and go back on together.
    map.once('styledata', async () => {
      if (map && lastRiderPoint) await addRiderLayers(map, lastRiderPoint)
      void drawRoute()
    })
  },
)

watch(
  () => [props.rider?.stale, props.rider?.headingDeg],
  () => applyRiderPaint(),
)

onMounted(() => {
  void build()
})

onBeforeUnmount(() => {
  cancelAnimation?.()
  stopHalo()
  pickupMarker?.remove()
  dropoffMarker?.remove()
  // The rider's layers go with the map itself; only the animation frame would
  // outlive it, and a rAF still calling setPaintProperty on a removed map is
  // the one thing here that throws after navigation.
  map?.remove()
  map = null
})
</script>

<template>
  <figure class="delivery-map">
    <div
      v-if="drawable && !failed"
      ref="container"
      class="delivery-map__canvas"
      :style="{ height }"
      role="img"
      :aria-label="caption"
    />
    <div v-else class="delivery-map__fallback" :style="{ minHeight: '96px' }">
      <span class="delivery-map__fallback-mark" aria-hidden="true">◈</span>
      <p>{{ caption }}</p>
    </div>

    <figcaption v-if="drawable && !failed" class="delivery-map__caption">
      <span class="delivery-map__caption-text">{{ caption }}</span>
      <span v-if="!ready" class="delivery-map__loading">Loading map…</span>
    </figcaption>
  </figure>
</template>

<style>
/*
 * Unscoped on purpose: the markers are real DOM elements handed to Mapbox,
 * which reparents them into its own overlay outside this component's tree, so
 * a scoped attribute would never reach them.
 */
.delivery-map {
  margin: 0;
  border-radius: 14px;
  overflow: hidden;
  border: 1px solid var(--border, rgba(0, 0, 0, 0.1));
  background: var(--surface-2, #f3f4f6);
}

.delivery-map__canvas {
  width: 100%;
}

.delivery-map__fallback {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 16px;
  color: var(--text-muted, #6b7280);
  font-size: 0.85rem;
}

.delivery-map__fallback-mark {
  font-size: 1.2rem;
  opacity: 0.5;
}

.delivery-map__fallback p {
  margin: 0;
}

.delivery-map__caption {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding: 8px 12px;
  font-size: 0.82rem;
  color: var(--text-muted, #6b7280);
  background: var(--surface, #fff);
  border-top: 1px solid var(--border, rgba(0, 0, 0, 0.08));
}

.delivery-map__loading {
  opacity: 0.7;
  white-space: nowrap;
}

/* The shop: a square, because it does not move. */
.delivery-map__pin {
  width: 14px;
  height: 14px;
  border: 2px solid #fff;
  box-shadow: 0 1px 4px rgba(0, 0, 0, 0.35);
}

.delivery-map__pin--pickup {
  background: #f59e0b;
  border-radius: 3px;
}

/* The door: a circle, distinguishable from the shop without reading a label. */
.delivery-map__pin--dropoff {
  background: #10b981;
  border-radius: 50%;
}

</style>
